variables:
# Setup AWS Role access
  # Gitlab provides us with OIDC tokens in environment variables, but not files
  # We've made up a file to echo it to.
  AWS_WEB_IDENTITY_TOKEN_FILE: /var/tmp/aws_token
  # Deployment jobs running only on master should use role/service/gitlab-ci-master
  AWS_ROLE_ARN: arn:aws:iam::783153433147:role/gitlab

default:
  id_tokens:
    AWS_OIDC_TOKEN:
      aud: sts.amazonaws.com
  before_script:
    - echo "${AWS_OIDC_TOKEN}" > $AWS_WEB_IDENTITY_TOKEN_FILE

test_aws:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws sts get-caller-identity

test_gcp:
  variables:
    GCP_TOKEN_FILE: /var/tmp/gcp_token
    GOOGLE_APPLICATION_CREDENTIALS: .gcp-creds.json
  id_tokens:
    GCP_OIDC_TOKEN:
      # Has to be the project number, not ID
      aud: //iam.googleapis.com/projects/948494648501/locations/global/workloadIdentityPools/gitlab/providers/gitlab
  image:
    name: google/cloud-sdk
  script:
    - echo "${GCP_OIDC_TOKEN}" > $GCP_TOKEN_FILE
    - ./test_gcp_account.sh
