presentation.html: presentation.md
	npx @marp-team/marp-cli --html presentation.md

presentation.pdf: presentation.md
	npx @marp-team/marp-cli --html presentation.md --allow-local-files -o presentation.pdf
