name: Continous Integration Deployment
on:
  push:
    branches:
      - master
      - force-ci

defaults:
  run:
    shell: bash

jobs:
  deploy-aws:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::783153433147:role/github-actions
        aws-region: us-east-1
    - name: Check our identity
      run: |
        aws sts get-caller-identity

  deploy-gcp:
    name: Test GCP Credentails
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    -
      id: "auth"
      # Get the GKE credentials so we can deploy to the cluster
      name: 'Gcloud Auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/948494648501/locations/global/workloadIdentityPools/deployment/providers/github-actions'
        service_account: 'github-ci-deployments@tcb-ci-test.iam.gserviceaccount.com'
        token_format: 'access_token'
        id_token_include_email: true
